# Generated by Django 5.0.1 on 2024-04-16 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcs_operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightpermission',
            name='status_code',
            field=models.CharField(choices=[('granted', 'granted'), ('denied', 'denied'), ('pending', 'pending')], default='pending', help_text='Permissions', max_length=20),
        ),
    ]
